### ISSUE TITLE
StackOverflow on Idea 2022.2

### ISSUE THREAD

**Issue by TechnicalRhino** [organics2016/pojo2json#22]
```java.lang.StackOverflowError
	at com.intellij.psi.impl.compiled.ClsElementImpl.isValid(ClsElementImpl.java:57)
	at com.intellij.psi.impl.compiled.ClsElementImpl.isValid(ClsElementImpl.java:58)
	at com.intellij.psi.impl.compiled.ClsElementImpl.isValid(ClsElementImpl.java:58)
	at com.intellij.psi.impl.compiled.ClsElementImpl.isValid(ClsElementImpl.java:58)
	at com.intellij.psi.impl.compiled.ClsElementImpl.isValid(ClsElementImpl.java:58)
	at com.intellij.psi.impl.compiled.ClsElementImpl.isValid(ClsElementImpl.java:58)
	at com.intellij.psi.impl.source.PsiClassReferenceType.isValid(PsiClassReferenceType.java:59)
	at com.intellij.psi.impl.TypeCorrector$PsiCorrectedClassType.isValid(TypeCorrector.java:236)
	at com.intellij.psi.util.PsiUtil.ensureValidType(PsiUtil.java:1275)
	at com.intellij.psi.util.PsiUtil.ensureValidType(PsiUtil.java:1256)
	at com.intellij.psi.EmptySubstitutor.put(EmptySubstitutor.java:53)
	at com.intellij.psi.impl.JavaClassSupersImpl.composeSubstitutors(JavaClassSupersImpl.java:132)
	at com.intellij.psi.impl.JavaClassSupersImpl.getSuperSubstitutorWithCaching(JavaClassSupersImpl.java:99)
	at com.intellij.psi.impl.JavaClassSupersImpl.getSuperClassSubstitutor(JavaClassSupersImpl.java:55)
	at com.intellij.psi.util.TypeConversionUtil.getMaybeSuperClassSubstitutor(TypeConversionUtil.java:1234)
	at com.intellij.psi.util.TypeConversionUtil.getSuperClassSubstitutor(TypeConversionUtil.java:1220)
	at com.intellij.psi.util.PsiUtil.substituteType(PsiUtil.java:1180)
	at com.intellij.psi.util.PsiUtil.substituteTypeParameter(PsiUtil.java:1153)
	at com.intellij.psi.util.PsiUtil.extractIterableTypeParameter(PsiUtil.java:1139)
	at ink.organics.pojo2json.parser.POJO2JSONParser.parseFieldValueType(POJO2JSONParser.java:200)
	at ink.organics.pojo2json.parser.POJO2JSONParser.parseFieldValueType(POJO2JSONParser.java:201)
	at ink.organics.pojo2json.parser.POJO2JSONParser.parseFieldValueType(POJO2JSONParser.java:201)
	at ink.organics.pojo2json.parser.POJO2JSONParser.parseFieldValueType(POJO2JSONParser.java:201)
	at ink.organics.pojo2json.parser.POJO2JSONParser.parseFieldValueType(POJO2JSONParser.java:201)
	at ink.organics.pojo2json.parser.POJO2JSONParser.parseFieldValueType(POJO2JSONParser.java:201)
	at ink.organics.pojo2json.parser.POJO2JSONParser.parseFieldValueType(POJO2JSONParser.java:201)
	at ink.organics.pojo2json.parser.POJO2JSONParser.parseFieldValueType(POJO2JSONParser.java:201)
	at ink.organics.pojo2json.parser.POJO2JSONParser.parseFieldValueType(POJO2JSONParser.java:201)
```

Can't Provide the POJO

**Comment by organics2016** [comment]
This may be a bug. Can you provide your class?

**Comment by organics2016** [comment]
This looks like the list field in your class references the class itself

**Comment by TechnicalRhino** [comment]
@organics2016 cannot provide the class because it's not open source. But it has no self referencing fields.

**Comment by organics2016** [comment]
OK, You currently provide insufficient information to locate the problem.
I can only guess your idea runtime memory is too small, and the reference level of your class cannot be readed in the memory before it exceeds 500.

If you are using the latest version, this has passed all test cases.
[https://github.com/organics2016/pojo2json/tree/master/src/test/java/testdata/java](https://github.com/organics2016/pojo2json/tree/master/src/test/java/testdata/java)
If you still feel the problem, you can try to reproduce it here.
