### ISSUE TITLE
在 IntelliJ IDEA 2024.3 (Ultimate Edition) 上总是报错

### ISSUE THREAD

**Issue by neilwyh** [organics2016/pojo2json#42]
插件版本：2.1.0

错误信息：
```
com.intellij.diagnostic.PluginException: Cannot create class ink.organics.pojo2json.ProjectViewPopupMenuAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=POJO to JSON, id=ink.organics.pojo2json, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2024.3/plugins/pojo2json, version=2.1.0, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Properties, id=com.intellij.properties, moduleName=intellij.properties/copyright, descriptorPath=intellij.properties.copyright.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/properties, version=243.21565.193, package=com.intellij.lang.properties.copyright, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.terminal, descriptorPath=intellij.java.terminal.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=243.21565.193, package=com.intellij.java.terminal, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.performancePlugin, descriptorPath=intellij.java.performancePlugin.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=243.21565.193, package=com.intellij.java.performancePlugin, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.compiler.charts, descriptorPath=intellij.java.compiler.charts.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=243.21565.193, package=com.intellij.java.compiler.charts, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=/Applications/IntelliJ IDEA.app/Contents/lib, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=/Applications/IntelliJ IDEA.app/Contents/lib, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=/Applications/IntelliJ IDEA.app/Contents/lib, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.jvm.analysis.impl, descriptorPath=intellij.jvm.analysis.impl.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.vcs, descriptorPath=intellij.java.vcs.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.unscramble, descriptorPath=intellij.java.unscramble.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.structuralSearch, descriptorPath=intellij.java.structuralSearch.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=/Applications/IntelliJ IDEA.app/Contents/lib, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.featuresTrainer, descriptorPath=intellij.java.featuresTrainer.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=243.21565.193, package=null, isBundled=true), PluginDescriptor(name=Properties, id=com.intellij.properties, descriptorPath=plugin.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/properties, version=243.21565.193, package=com.intellij.lang.properties, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, descriptorPath=plugin.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=243.21565.193, package=null, isBundled=true), ))
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:927)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:903)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:944)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.instantiate(ActionManagerImpl.kt:1462)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertStub(ActionManagerImpl.kt:1708)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.getAction(ActionManagerImpl.kt:2198)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$getAction(ActionManagerImpl.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:411)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:393)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:401)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:413)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:413)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:413)
	at com.intellij.ide.util.gotoByName.GotoActionModel.buildGroupMappings(GotoActionModel.java:113)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor$fetchWeightedElements$1$1.invokeSuspend(ActionSearchEverywhereContributor.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:111)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$BuildersKt__BuildersKt(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlockingWithParallelismCompensation(Builders.kt:60)
	at kotlinx.coroutines.BuildersKt.runBlockingWithParallelismCompensation(Unknown Source)
	at kotlinx.coroutines.internal.intellij.IntellijCoroutines.runBlockingWithParallelismCompensation(intellij.kt:41)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable$lambda$0(coroutines.kt:147)
	at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext$lambda$5(context.kt:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.silenceGlobalIndicator(CoreProgressManager.java:1041)
	at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext(context.kt:107)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:77)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:140)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:123)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements$lambda$0(ActionSearchEverywhereContributor.kt:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.kt:97)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:182)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:206)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:74)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:83)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Cannot find suitable constructor, expected (), (CoroutineScope), (Application), or (Application, CoroutineScope)
	at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:912)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:918)
	... 60 more
```

**Comment by organics2016** [comment]
等v2.1.1推送试试。可能是2024.3依赖结构修改导致的
https://intellij-support.jetbrains.com/hc/en-us/community/posts/21479962703890-JSON-plugin-dependency-cannot-be-resolved
